# Generated by Django 4.0 on 2025-08-18 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='categoria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
