# Generated by Django 4.0 on 2025-08-21 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0003_categoria_transacao_nome_transacao_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='cor',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
